Imports System
Imports System.Collections.Generic
Imports System.Configuration
Imports System.Data
Imports System.Linq
Imports System.Windows
Imports DevExpress.Xpf.Core
Imports System.Data.Entity
Imports Scaffolding.ManyToMany.Model
Imports DevExpress.Mvvm.DataAnnotations

Namespace Scaffolding.ManyToMany
    ''' <summary>
    ''' Interaction logic for App.xaml
    ''' </summary>
    Partial Public Class App
        Inherits Application

        Protected Overrides Sub OnStartup(ByVal e As StartupEventArgs)
            MyBase.OnStartup(e)
            Database.SetInitializer(Of SchoolContext)(New SchoolContextInitializer())
            MetadataLocator.Default = MetadataLocator.Create().AddMetadata(Of SchoolContextMetadata)()
        End Sub

        Private Sub OnAppStartup_UpdateThemeName(ByVal sender As Object, ByVal e As StartupEventArgs)
            DevExpress.Xpf.Core.ApplicationThemeHelper.UpdateApplicationThemeName()
        End Sub
    End Class
    Public Class SchoolContextMetadata
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Student))
            builder.Property(Function(x) x.StudentId).NotAutoGenerated()
            builder.Property(Function(x) x.CoursesAttending).NotAutoGenerated()
        End Sub
        Public Shared Sub BuildMetadata(ByVal builder As MetadataBuilder(Of Course))
            builder.Property(Function(x) x.CourseId).NotAutoGenerated()
            builder.Property(Function(x) x.Students).NotAutoGenerated()
        End Sub
    End Class
End Namespace
