using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Windows;
using DevExpress.Xpf.Core;
using System.Data.Entity;
using Scaffolding.ManyToMany.Model;
using DevExpress.Mvvm.DataAnnotations;
using DevExpress.Internal;

namespace Scaffolding.ManyToMany {
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application {
        protected override void OnStartup(StartupEventArgs e) {
            base.OnStartup(e);
            ApplicationThemeHelper.UpdateApplicationThemeName();
            DbEngineDetector.PatchConnectionStringsAndConfigureEntityFrameworkDefaultConnectionFactory();
            Database.SetInitializer<SchoolContext>(new SchoolContextInitializer());
            MetadataLocator.Default = MetadataLocator.Create().AddMetadata<SchoolContextMetadata>();
        }

        protected override void OnExit(ExitEventArgs e) {
            ApplicationThemeHelper.SaveApplicationThemeName();
        }
    }
    public class SchoolContextMetadata {
        public static void BuildMetadata(MetadataBuilder<Student> builder) {
            builder.Property(x => x.StudentId).NotAutoGenerated();
            builder.Property(x => x.CoursesAttending).NotAutoGenerated();
        }
        public static void BuildMetadata(MetadataBuilder<Course> builder) {
            builder.Property(x => x.CourseId).NotAutoGenerated();
            builder.Property(x => x.Students).NotAutoGenerated();
        }
    }
}
