//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scaffolding.ManyToMany.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchoolContextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchoolContextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scaffolding.ManyToMany.Localization.SchoolContextResources", typeof(SchoolContextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

			        public static string Course { get { return ResourceManager.GetString("Course", resourceCulture); } }
		        public static string CoursePlural { get { return ResourceManager.GetString("CoursePlural", resourceCulture); } }
		        public static string Course_CourseId { get { return ResourceManager.GetString("Course_CourseId", resourceCulture); } }
		        public static string Course_Title { get { return ResourceManager.GetString("Course_Title", resourceCulture); } }
		        public static string Student { get { return ResourceManager.GetString("Student", resourceCulture); } }
		        public static string StudentPlural { get { return ResourceManager.GetString("StudentPlural", resourceCulture); } }
		        public static string Student_StudentId { get { return ResourceManager.GetString("Student_StudentId", resourceCulture); } }
		        public static string Student_FirstName { get { return ResourceManager.GetString("Student_FirstName", resourceCulture); } }
		        public static string Student_LastName { get { return ResourceManager.GetString("Student_LastName", resourceCulture); } }
	
    }
}

